apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: url-shortener
  namespace: '<PROJECT_NUMBER>'
  labels:
    cloud.googleapis.com/location: australia-southeast1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: <SERVICE_ACCOUNT>
      containers:
      - name: url-shortener
        image: <CONTAINER_IMAGE>
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: DOMAIN_NAME
          value: localhost
        - name: PROTOCOL
          value: https
        - name: PROJECT_ID
          value: <PROJECT_ID>
        - name: DATABASE_ID
          value: <DATABASE_ID>
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
