apiVersion: run.googleapis.com/v1
kind: Service
metadata:
  labels:
    cloud.googleapis.com/location: us-central1
  name: url-shortener
  namespace: <PROJECT_NUMBER>
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: <CONTAINER_IMAGE>
        run.googleapis.com/execution-environment: gen2
    spec:
      template:
        spec:
          containers:
          - env:
            - name: DOMAIN_NAME
              value: localhost
            - name: PORT
              value: 8080
            - name: PROTOCOL
              value: https
            - name: PROJECT_ID
              value: <PROJECT_ID>
            - name: DATABASE_ID
              value: <DATABASE_ID>
            image: <CONTAINER_IMAGE>
            resources:
              limits:
                cpu: 1000m
                memory: 2Gi
          serviceAccountName: <SERVICE_ACCOUNT>
          timeoutSeconds: '3600'
              
              