apiVersion: run.googleapis.com/v1
kind: Service
metadata:
  labels:
    cloud.googleapis.com/location: us-central1
  name: url-shortener
  namespace: 12345
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: lol
        run.googleapis.com/execution-environment: gen2
    spec:
      template:
        spec:
          containers:
          - env:
            - name: DOMAIN_NAME
              value: localhost
            - name: PORT
              value: 8080
            - name: PROTOCOL
              value: https
            - name: PROJECT_ID
              value: 54321
            - name: DATABASE_ID
              value: sample
            image: lol
            resources:
              limits:
                cpu: 1000m
                memory: 2Gi
          serviceAccountName: yep
          timeoutSeconds: '3600'
              
              