name: cd-application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Go setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build production
        working-directory: ./scripts
        run: ./build-prod.sh
      
      - name: Deployment - activate service account
        uses: google-github-actions/auth@v1
        env:
          gcp_workload_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
          gcp_sa_name: ${{ secrets.GCP_SA_NAME }}
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ env.gcp_workload_provider }}
          service_account: ${{ env.gcp_sa_name }}

      - name: Deployment - set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: ">= 363.0.0"
          
      # Differing opinions on this.
      # Is it best to build with Docker here, or send to gcloud build?
      # I've typically sent to gcloud build, but have seen a lot of local Docker calls lately.
      - name: Build Docker image
        run: echo "Placeholder"

      # TODO: Service manifest.
      - name: Deploy to Cloud Run
        run: gcloud run deploy url-shortener
          