name: cd-infrastructure

on:
  push:
      branches: [ main ]
      paths:
      - "application/**"
  workflow_dispatch:

env:
  gcp_project: ${{ secrets.GCP_PROJECT }}
  gcp_sa_name: ${{ secrets.GCP_SA_NAME }}
  gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
  gcp_state_bucket: ${{ secrets.GCP_STATE_BUCKET }}
  env_name: prod
  app_name: url-shortener

jobs:  
  apply:
    name: apply
    runs-on: ubuntu-22.04

    steps:
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0-alpha3

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Activate service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.gcp_sa_key }}
        
      - name: Tofu init
        run: |
          cd infrastructure/environments/prod
          tofu init -backend-config="bucket=${{ env.gcp_state_bucket }}"

      - name: Tofu apply
        run: |
          cd infrastructure/environments/prod
          tofu apply -auto-approve -var "project_id=${{ env.gcp_project }}" \
          -var "env=${{ env.env_name }}" \
          -var "app_name=${{ env.app_name }}"
  
