name: ci-infrastructure

on:
  pull_request:
    branches: [ main ]
    paths:
      - "infrastructure/**"

permissions:
  id-token: write
  contents: read

env:
  gcp_project: ${{ secrets.GCP_PROJECT }}
  gcp_sa_name: ${{ secrets.GCP_SA_NAME }}
  gcp_workload_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
  gcp_state_bucket: ${{ secrets.GCP_STATE_BUCKET }}
  repo_id: ${{ secrets.REPO_ID }}
  repo_owner_id: ${{ secrets.REPO_OWNER_ID }}
  env_name: prod
  app_name: url-shortener

jobs:
  style:
    name: style
    runs-on: ubuntu-22.04

    steps:
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0-alpha3

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Run format check
        run: |
          cd infrastructure
          tofu fmt -check -recursive
          
  
  plan:
    name: plan
    runs-on: ubuntu-22.04

    steps:
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0-alpha3

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Activate service account
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ env.gcp_workload_provider }}
          service_account: ${{ env.gcp_sa_name }}
        
      - name: Tofu init
        run: |
          cd infrastructure/environments/prod
          tofu init -backend-config="bucket=${{ env.gcp_state_bucket }}"

      - name: Tofu validate
        run: |
          cd infrastructure/environments/prod
          tofu validate

      - name: Tofu plan
        run: |
          cd infrastructure/environments/prod
          tofu plan -var "project_id=${{ env.gcp_project }}" \
          -var "env=${{ env.env_name }}" \
          -var "app_name=${{ env.app_name }}" \
          -var "sa_provisioner_name=${{ env.gcp_sa_name }}"
          -var "github_repo_id=${{ env.repo_id }}"
          -var "github_repo_owner_id=${{ env.repo_owner_id }}"
  
