name: ci-application

on:
  pull_request:
    branches: [ main ]

jobs:
  style:
    name: style
    runs-on: ubuntu-22.04

    steps:
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0-alpha3

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Run format check
        run: |
          cd infrastructure
          test -z $(tofu fmt -recursive)
  
  plan:
    name: plan
    runs-on: ubuntu-22.04

    steps:
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0-alpha3

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Tofu init
        run: |
          cd infrastructure/environments/prod
          tofu init -backend-config terraform.tfbackend

      - name: Tofu plan
        run: |
          cd infrastructure/environments/prod
          terraform plan -var-file terraform.tfvars
  
